# -*- coding: utf-8 -*-
"""Fake_News_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1trLFlKypW0W4SHZUl9hTBQKcGqrgJtDY
"""

from google.colab import files

print("Upload Fake.csv")
files.upload()

print("Upload True.csv")
files.upload()

import os
print(os.listdir())

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

fake_df = pd.read_csv('Fake.csv')
true_df = pd.read_csv('True.csv')

print(f"Fake articles: {len(fake_df)}")
print(f"Real articles: {len(true_df)}")

print("\nFake.csv sample:")
print(fake_df.head(3))

print("\nTrue.csv sample:")
print(true_df.head(3))

print("\nColumns:", fake_df.columns.tolist())

fake_df['label'] = 0
true_df['label'] = 1

df = pd.concat([fake_df, true_df], ignore_index=True)
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

print(f"Total articles: {len(df)}")
print(f"Fake: {len(df[df['label']==0])}")
print(f"Real: {len(df[df['label']==1])}")

print("Missing values:")
print(df.isnull().sum())

print("\nData types:")
print(df.dtypes)

df['text_length'] = df['text'].astype(str).apply(len)
print(f"\nAvg length: {df['text_length'].mean():.0f} chars")

plt.figure(figsize=(15,5))

plt.subplot(1,3,1)
plt.hist(df[df['label']==0]['text_length'], alpha=0.7, bins=50, label='Fake', color='red')
plt.hist(df[df['label']==1]['text_length'], alpha=0.7, bins=50, label='Real', color='green')
plt.legend()
plt.title('Article Length')

plt.subplot(1,3,2)
df['label'].value_counts().plot(kind='bar', color=['red','green'])
plt.xticks([0,1],['Fake','Real'])
plt.title('Dataset Balance')

plt.subplot(1,3,3)
df['subject'].value_counts().head(10).plot(kind='barh')
plt.title('Top Subjects')

plt.tight_layout()
plt.show()

df.to_csv('prepared_news_dataset.csv', index=False)
print("Saved as prepared_news_dataset.csv")

from google.colab import files
files.download('prepared_news_dataset.csv')

import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

nltk.download('stopwords')
nltk.download('punkt')

stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()

def clean_text(text):
    text = str(text)
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    text = text.lower()
    text = re.sub(r'\s+', ' ', text).strip()
    return text

def preprocess(text):
    words = text.split()
    words = [w for w in words if w not in stop_words]
    words = [stemmer.stem(w) for w in words]
    return ' '.join(words)

# Test the function
test = "BREAKING: Scientists discover shocking truth!!!"
print("Original:", test)
print("Cleaned:", clean_text(test))
print("Preprocessed:", preprocess(clean_text(test)))

print("Cleaning text...")
df['clean_text'] = df['text'].apply(clean_text)
df['clean_content'] = df['clean_text'].apply(preprocess)

print("Done!")
print("\nBefore:")
print(df['text'].iloc[0][:200])
print("\nAfter:")
print(df['clean_content'].iloc[0][:200])

df[['clean_content', 'label']].to_csv('cleaned_news.csv', index=False)
print("Saved as cleaned_news.csv")

from google.colab import files
files.download('cleaned_news.csv')

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import joblib

X = df['clean_content']
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(f"Training samples: {len(X_train)}")
print(f"Testing samples: {len(X_test)}")

vectorizer = TfidfVectorizer(max_features=5000)

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

print(f"Training matrix: {X_train_vec.shape}")
print(f"Testing matrix: {X_test_vec.shape}")

model = LogisticRegression(max_iter=1000)
model.fit(X_train_vec, y_train)

print("Model training complete!")

y_pred = model.predict(X_test_vec)
accuracy = accuracy_score(y_test, y_pred)

print(f"Accuracy: {accuracy:.2%}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=['Fake', 'Real']))

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Fake', 'Real'],
            yticklabels=['Fake', 'Real'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title(f'Confusion Matrix (Accuracy: {accuracy:.2%})')
plt.show()

joblib.dump(model, 'fake_news_model.pkl')
joblib.dump(vectorizer, 'vectorizer.pkl')

print("Model saved as fake_news_model.pkl")
print("Vectorizer saved as vectorizer.pkl")

from google.colab import files
files.download('fake_news_model.pkl')
files.download('vectorizer.pkl')

def predict_news(text):
    cleaned = clean_text(text)
    processed = preprocess(cleaned)
    vec = vectorizer.transform([processed])
    pred = model.predict(vec)[0]
    proba = model.predict_proba(vec)[0]
    return pred, proba

test_articles = [
    "Breaking: Scientists discover cure for cancer but hidden by big pharma",
    "Stock market rises 2% following positive economic data",
    "Aliens found on Mars - NASA covering it up",
    "President signs new law to improve healthcare access"
]

for i, article in enumerate(test_articles):
    pred, proba = predict_news(article)
    result = "REAL" if pred == 1 else "FAKE"
    confidence = proba[1] if pred == 1 else proba[0]
    print(f"\nArticle {i+1}:")
    print(f"Text: {article[:50]}...")
    print(f"Result: {result} (Confidence: {confidence:.2%})")

import os
print("Files in current directory:")
for file in os.listdir():
    if file.endswith('.pkl') or file.endswith('.csv'):
        size = os.path.getsize(file) / (1024*1024)
        print(f"  📄 {file} - {size:.2f} MB")

import os

duplicates = ['True (1).csv', 'True (2).csv', 'Fake (1).csv', 'Fake (2).csv']

for file in duplicates:
    if file in os.listdir():
        os.remove(file)
        print(f"Removed: {file}")

print("\n Cleaned up duplicates!")
print("\nCurrent files:")
for file in os.listdir():
    size = os.path.getsize(file) / (1024*1024)
    print(f"  📄 {file} - {size:.2f} MB")

from google.colab import files

print("Downloading model file...")
files.download('fake_news_model.pkl')

print("Downloading vectorizer file...")
files.download('vectorizer.pkl')

print("Downloading cleaned dataset (optional)...")
files.download('cleaned_news.csv')